Agregando codigo de conducta
reactjs-hispano/code_of_conduct pull request #1
Opened 2020-04-20 21:28 UTC by fforres

2020-04-20 22:29 UTC, bjrmatos requested changes

2020-04-20 22:29 UTC, bjrmatos commented on README.md
> +¿Has visto como luego de algunos eventos, conversaciones, todos hablan de "aquella v" que causó un mal rato a uno o más participantes?. Que no sea de ti de quien hablen :)
creo que hubo un pequeño typo aquí en la parte de `hablan de "aquella v"`, por el resto todo me parece excelente!

2020-04-21 05:11 UTC, fforres commented on README.md
> +¿Has visto como luego de algunos eventos, conversaciones, todos hablan de "aquella v" que causó un mal rato a uno o más participantes?. Que no sea de ti de quien hablen :)
Fixeado @bjrmatos  :D

2020-04-21 16:50 UTC, bjrmatos approved these changes
all good

2020-04-22 21:12 UTC, merged